### ISSUE TITLE
Possibility to list/display outdated lib

### ISSUE THREAD

**Issue by ghost** [Streetwalrus/longoverdue#1]
I wondered if it was possible to show the lib that is referred to make it possible to assess how urgent a restart is (sure you can guess some things from pacman updates, but maybe there were a lot of lib updates).

Besides my rather cosmetic request: very good replacement of overdue, I like it!

**Comment by 9ary** [comment]
Actually, this is already implemented: `longoverdue info <regex>` (the regex is passed to `pgrep`).

I can probably add a verbose switch to the main command as well.

**Comment by 9ary** [comment]
@IdleGandalf is this still something you want or can I close this?

**Comment by ghost** [comment]
Hm a flag or something to show it in main out would be pretty awesome, alternative adding/modifying info would be an option too. I tested info and it requires to specify the program, so info is not really suited to get an overview after an update in the current state.

**Comment by 9ary** [comment]
That's what I thought. I'll see what I can do.

**Comment by 9ary** [comment]
Here you go. I hope you like what I came up with.

**Comment by ghost** [comment]
Looks good. Thanks!
